- name: Reload Cloudflare Tunnel Systemd Unit
  systemd_service:
    name: cloudflare-tunnel
    state: started
    daemon_reload: true

- name: Restart Cloudflare Tunnel Systemd Unit
  systemd_service:
    name: cloudflare-tunnel
    state: restarted
