//
= Ansible Infrastructure

This post is going to be another boilerplate, the last before actually
getting to creating infratructure services on CoreOS.

At this point, if you've been following the series up to now, there
are a pair of devices running CoreOS on the network. They can be Intel
or ARM. Each has a user account with SSH access via an SSH key and `sudo` set to
allow commands as root with no password.

Again, there are numerous references and tutorials showing how to set
up Ansible. See link:references[References]. This document just
defines the working parameters of the infrastructure system for the
following posts.

The example playbooks in this and following posts all expect to be run
from the top of an Ansible file tree.

.**Minimal Ansible directory tree**
----
$ tree
.
├── ansible.cfg
└── inventory.yaml

1 directory, 2 files
----

This tree will expand as playbooks are added to prepare and deploy the
network services to the server devices.

== Minimal Ansible Configuration

Ansible looks for a configuration file, `ansible.cfg` in the current
working directory when Ansible is invoked. The following minimal
configuration file directs Ansible also to find the inventory in the
current working directory.

.`ansible.cfg`
[source,ini]
----
[defaults]
inventory = ./inventory.yaml
deprecation_warnings = False
----

== Infrastructure Devices

The network infrastructure devices in this case are a pair of hosts
running https://fedoraproject.org/coreos[Fedora CoreOS]. They are
configured on the network with fixed IP addresses. They are accessable
via SSH using a key pair on the `core` account. Each device host key has been
added to the local SSH `known_hosts` list by logging in one time. That account has
`sudo` access with no password. It has Ansible installed as a layered
package so that the required Python packages are present.

For purposes of the example, these are the the access parameters,
expressed as an Ansible YAML inventory file:

.`inventory.yaml`
[source,yaml]
----
---
infrastructure:
  vars:
    ansible_user: core
    ansible_ssh_private_key_file: secrets/infra-ansble-ed25519
  hosts:
    infra1:
      ansible_host: 192.168.2.185
    infra2:
      ansible_host: 192.168.2.186
----

== Checking Connectivity



== References

* https://docs.ansible.com/ansible/latest/getting_started/get_started_ansible.html#get-started-ansible[Getting Started with Ansible]
* https://docs.ansible.com/ansible/latest/inventory_guide/index.html[Ansible Inventory]


