= Provisioning CoreOS

Installing CoreOS on a new system involves just booting a copy of the
installation media with the configuration file
(link:./COREOS_CONFIG.adoc[produced earlier]) embedded. On most
systems, the installation media is a USB stick and the target storage
is an internal disk or SSD. The CoreOS image is copied bitwise to the
destination and is then tuned according to the configuration file. On
systems like the Raspberry Pi, that boot from an integrated SD card
slot, this bootable media is the target device as well.

It is possible, on systems capable of network boot by DHCP/PXE, to
boot in memory over a network and then to install to local disk. In
that case the configuration file is retrieved by HTTP(S) from a local
web site. This demonstration will only use bootable media.

Both of the procedures shown here are derived from the
https://docs.fedoraproject.org/en-US/fedora-coreos/[Fedora CoreOS
Documentation], specifically the instructions for
https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[bare
metal] and
https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[Raspberry
Pi 4: EKD2 Combined Fedora CoreOS + EDK2 Firmware Disk].

== References

* https://coreos.github.io/coreos-installer/[coreos-installer] +
  Usage and arguments for the CoreOS installer binary.  This can be
  run from a live ISO or on a second host to write to the boot media.

* https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[CoreOS
  on Bare Metal] +
  How to install CoreOS on Bare Metal. This includes variants for PXE,
  and Live ISO installations.

* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[CoreOS
  on Raspberry Pi 4] +
  How to install CoreOS on Raspberry Pi 4 or 5. This includes
  instructions for installing EFI boot components that are not present
  in the Pi boot firmware.

* https://github.com/coreos/ignition[Ignition] +
  Ignition is the engine that applies the provided configuration to a
  new CoreOS instance on first boot.

* https://github.com/pbatard/UEFI-Shell[UEFI-Shell] +
  a UEFI Shell for built from EDK2 sources

* https://github.com/pftf/RPi4/[Raspberry Pi 4 UEFI Firmware Images] +
  A build of the UEFI-Shell specifically for Rasberry Pi 4
 
