= Provisioning CoreOS

Installing CoreOS on a new system involves just booting a copy of the
installation media with the configuration file
(link:./COREOS_CONFIG.adoc[produced earlier]) embedded. On most
systems, the installation media is a USB stick and the target storage
is an internal disk or SSD. The CoreOS image is copied bitwise to the
destination and is then tuned according to the configuration file. On
systems like the Raspberry Pi, that boot from an integrated SD card
slot, this bootable media is the target device as well.

It is possible, on systems capable of network boot by DHCP/PXE, to
boot in memory over a network and then to install to local disk. In
that case the configuration file is retrieved by HTTP(S) from a local
web site. This demonstration will only use bootable media.

Both of the procedures shown here are derived from the
https://docs.fedoraproject.org/en-US/fedora-coreos/[Fedora CoreOS
Documentation], specifically the instructions for
https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[Bare
Metal] Intel and
https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[Raspberry
Pi 4]:
https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_fedora_coreos_edk2_firmware_disk[EKD2
Combined Fedora CoreOS + EDK2 Firmware Disk]. The bare metal procedure
is very close to identical.  For the Raspberry Pi 4 procedure the
individual steps have been scripted to a single command, but that is
not strictly necessary.

== Bare Metal Installation - Intel

The Bare Metal installation is the most straightforward. It consists
of just five steps:

. Download CoreOS ISO image
. Customize ISO image - Destination Disk and Ignition File
. Write ISO to USB Stick
. Boot from the USB stick
. Boot from the target disk

This example assumes that the Ignition file for the host is
`coreos-config.ign` and the destination disk is `/dev/sda`. The
invocation lets most of the CLI arguments default:

* archtecture: x86_64
* platform: metal
* stream: stable
* format: ISO

The network configuration is allowed to default to DHCP for any NICs
that detect link.

----
# Download ISO if necessary. Write file name
IMAGE_FILE=$(coreos-installer download --format iso)
# Customize the ISO image for the target host
coreos-installer iso customize --dest-device /dev/sda --dest-ignition coreos-config.ign ${IMAGE_FILE}
# Write the ISO to bootable media
sudo dd if=${IMAGE_FILE} of=/dev/sda bs=1M status=progress
# Reset the local ISO file for next use
coreos-installer iso reset
----

Two things to note here about `coreos-installer download`

. It checks if the ISO file exists
locally, and if so, checks that it is current before trying to
download again.
. It writes the filename of the ISO file to `stdout` on exit. That
value can be used in following script lines.

The final step of the list above restores the ISO image for
next use. The image file is under 800MB, and so will fit on even very
small USB sticks.


== Raspberry Pi 4 Installation



== References

* https://coreos.github.io/coreos-installer/[coreos-installer] +
  Usage and arguments for the CoreOS installer binary.  This can be
  run from a live ISO or on a second host to write to the boot media.

* https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[CoreOS
  on Bare Metal] +
  How to install CoreOS on Bare Metal. This includes variants for PXE,
  and Live ISO installations.

* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[CoreOS
  on Raspberry Pi 4] +
  How to install CoreOS on Raspberry Pi 4 or 5. This includes
  instructions for installing EFI boot components that are not present
  in the Pi boot firmware.

* https://github.com/coreos/ignition[Ignition] +
  Ignition is the engine that applies the provided configuration to a
  new CoreOS instance on first boot.

* https://github.com/pbatard/UEFI-Shell[UEFI-Shell] +
  a UEFI Shell for built from EDK2 sources

* https://github.com/pftf/RPi4/[Raspberry Pi 4 UEFI Firmware Images] +
  A build of the UEFI-Shell specifically for Rasberry Pi 4
 
