= Deploying CoreOS

There are already a number of good resources for deploying CoreOS to
various systems. See <<references>>. This document focuses on the
particulars of configuring and deploying CoreOS as a base for small
and medium network infrastructure services.

== The Principle of Least Config

In keeping with the minimalist philosophy of CoreOS, the configuration
will apply only those settings necessary to boot the system and
provide remote access and configuration management. The first two are fairly
trivial, but the last involves a bit of system gymnastics.

The CoreOS configuration is applied at first boot and is provided to
the installer when writing the boot media to storage.

[source, yaml]
.`coreos-infra.bu`
----
---
# 1 - Specify the target and schema version
variant: fcos
version: 1.6.0

# 2 - Provide an ssh public key for the core user
passwd:
  users:
    - name: core
      ssh_authorized_keys_local:
        - infra-ansible-ed25519.pub

storage:
  files:

    # 3 - Define the system hostname
    - path: /etc/hostname
      contents:
        inline: |
          infra-01.example.com

    # 4a - A script to overlay the ansible packages and clean up
    - path: /usr/local/bin/install-overlay-packages
      user:
        name: root
      group:
        name: root
      mode: 0755
      contents:
        inline: |
          #!/bin/bash

          if [ -x /usr/bin/ansible ] ; then
            rm /usr/local/bin/install-overlay-packages
            systemctl disable install-overlay-packages
            rm /etc/systemd/system/install-overlay-packages.service
          else
            rpm-ostree install --assumeyes ansible
            systemctl reboot
          fi

systemd:
  units:

    # 4b - Define a one-time service to run at first boot
    - name: install-overlay-packages.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Overlay Packages
        After=systemd-resolved.service
        Before=zincati.service

        [Service]
        Type=oneshot
        ExecStart=/usr/local/bin/install-overlay-packages

        [Install]
        WantedBy=multi-user.target
----

=== 1 - Butane Preamble

The Butane configuration schema begins with two values that identify
the target OS and the schema version itself.

[source, yaml]
----
variant: fcos
version: 1.6.0
----

This indicates that the file targets Fedora CoreOS and the schema version is 1.6.0.
This assists the parser in validating the remainder of the configuration against the
indicated schema.

=== 2 - Core User - SSH Public Key

CoreOS deploys with two default users, `root` and `core`. The `root`
user is not intended for direct login. Neither has a password by
default. CoreOS is meant to be accessed by SSH on a network by the
`core` user.

[source, yaml]
----
passwd:
  users:
    - name: core
      ssh_authorized_keys_local:
        - infra-ansible-ed25519.pub
----

The `core` user already exists so no additional parameters need to be
provided. The user definition only specifies a public key file who's
contents will be inserted into the `authorized_keys` file of that
user.

The `ssh_authorized_keys_local` option above consists of a list
of filenames on the local machine that will be merged into the
ignition file during transformation. The directory containing that
file is provided on the `butane` command line using the `--files-dir` argument.

=== 3 - Hostname

=== 4 - Package Overlay

==== 4a - Overlay Script

==== 4b - One-time First Boot Service

= References

* https://coreos.github.io/butane/[Butane]

* https://coreos.github.com/ignition[Ignition]

* https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[CoreOS on Bare Metal]

* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[CoreOS on Raspberry Pi 4]

