= Deploying CoreOS

CoreOS installs by laying an image onto the boot disk and writing the
configuration file so that it is available on first boot. The initrd
for CoreOS contains the https://coreos.github.io/ignition/[Ignition]
module. The initrd runs in memory and so it can manipulate the system
disks if needed before they are mounted and control transfers to
systemd to complete the boot process.

The configuration created in
https://electron-swamp.blogspot.com/2025/01/coreos-configuration-less-is-right.html[the
previous post] defines just enough to provide access for the `core`
user over the network by SSH, and layers the Ansible packages over the
base. The remainder of the system customization will be defined and
executed using Ansible.

In this post we'll walk through the installer process for two
different light-weight target systems, and using two different
installation methods.

* CoreOS on Intel - Live Boot USB
* CoreOS on Raspberry Pi 4 - Write to Bootable SD Card

Both of these are also detailed in
https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/[Getting
Started with Fedora CoreOS] documentation. 

== The CoreOS Installer

CoreOS is installed using the
https://coreos.github.io/coreos-installer/[coreos-installer]
binary. On Fedora systems, the binary is available as an RPM. This
program writes the stock image to the disk and writes an Ignition
configuration file as well. Part of the installed image is an initial
ram-disk or `initrd`. That ram-disk runs in memory leaving the disk
free and unmounted, ready to apply the configuration, before mounting
the new disk and transferring control to the new system.

The `coreos-installer` has 5 sub-commands for managing the
installation process, but the only one needed for these cases is the
`install` command. The only required argument for `coreos-installer
install` is the target disk to write to. The important optional
arguments allow you to determine where to pull the image from, and
where to get the Ignition file from. Both can either pull from a
network or local disk.


== Raspberry Pi 4 - Install to SD Card

The method of installation used here is
https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_disk_mode_alternate_machine_disk_preparation[EDK2:Combined Disk Mode Alternate Machine Disk Preparation]
This method first lays down the CoreOS disk image and then adds the
EDK2 UEFI files needed for the Pi to boot. 

The arguments to the installer can be provided in one or more YAML
configuration files or on the command line. The configuration file
consists of a set of YAML key/value pairs, matching the CLI arguments
without the leading double-dash (--).

Installing for a Raspberry Pi means writing to an SD card. Insert the
card in a reader and attach it to your system.  Make sure to unmount
any filesystems on the card that might have been automounted and note
the device path. Note that any contents on the card will be
overwritten by the CoreOS image. 

The config file below defines the characteristics of the image to
write to the SD card.

.pi4-config.yaml
[source, yaml]
----
---
stream: stable
architecture: aarch64
platform: rpi4
console: ttyS0,115200,8n1
ignition-file: coreos-infra.ign
----

Assuming the SD card device file is `/dev/sdb` and the ignition file
is in the current working directory, the command to write the boot
image is this:

    sudo coreos-installer --config pi4-config.yaml /dev/sdb

----
sudo coreos-installer --architecture aarch64 --platform rpi4 \
     --ignition-file coreos-infra.ign /dev/sdb
----

== Intel x86_64 - Live USB



== References

* https://coreos.github.io/coreos-installer/[coreos-installer] +
  Usage and arguments for the CoreOS installer binary.  This can be
  run from a live ISO or on a second host to write to the boot media.

* https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[CoreOS
  on Bare Metal] +
  How to install CoreOS on Bare Metal. This includes variants for PXE,
  and Live ISO installations.

* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[CoreOS
  on Raspberry Pi 4] +
  How to install CoreOS on Raspberry Pi 4 or 5. This includes
  instructions for installing EFI boot components that are not present
  in the Pi boot firmware.

* https://github.com/coreos/ignition[Ignition] +
  Ignition is the engine that applies the provided configuration to a
  new CoreOS instance on first boot.

* https://github.com/pbatard/UEFI-Shell[UEFI-Shell] +
  a UEFI Shell for built from EDK2 sources

* https://github.com/pftf/RPi4/[Raspberry Pi 4 UEFI Firmware Images] +
  A build of the UEFI-Shell specifically for Rasberry Pi 4
 
