= Deploying CoreOS

CoreOS installs by laying an image onto the boot disk and writing the
configuration file so that it is available on first boot. The initrd
for CoreOS contains the https://coreos.github.io/ignition/[Ignition]
module. The initrd runs in memory and so it can manipulate the system
disks if needed before they are mounted and control transfers to
systemd to complete the boot process.

The Ignition file created in
https://electron-swamp.blogspot.com/2025/01/coreos-configuration-less-is-right.html[the
previous post] defines just enough to provide access for the `core`
user over the network by SSH, and layers the Ansible packages over the
base. The network configuration must be supplied by DHCP. The
remainder of the system customization will be defined and executed
using Ansible.

In this post we'll walk through the installer process for two
different light-weight target systems, and using two different
installation methods.

* CoreOS on Intel - Live Boot USB
* CoreOS on Raspberry Pi 4 - Write to Bootable SD Card

Both of these are detailed in
https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/[Getting
Started with Fedora CoreOS] documentation and those are the sources
for this procedure. Readers who are experienced booting from a USB or
with provisioning a Raspberry Pi can probably skip this page.

The remainder of this post details the specifics of the two instances
that will be used in later posts. 

== The CoreOS Installer

CoreOS is installed using the
https://coreos.github.io/coreos-installer/[coreos-installer]
binary. On Fedora systems, the binary is available as an RPM. This
program writes the stock image to the disk and writes an Ignition
configuration file as well. This customizes the media so it installs
to the correct destination and configures it on the first boot.

== Raspberry Pi 4 - Install to SD Card

The method of installation used here is
https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_disk_mode_alternate_machine_disk_preparation[EDK2:Combined
Disk Mode Alternate Machine Disk Preparation]

Raspberry Pi systems boot from an SD card installed on the board. The
`coreos-installer` writes the image and Ignition file to the SD card.
When the system boots for the first time, the configuration is applied
and the installation is complete.

The command below assumes that the ignition file is `coreos-infra.ign`
and that the target device is `/dev/sdb`. Adjust those values as
needed for your environment

----
sudo coreos-installer --stream stable --architecture aarch64 --platform rpi4 \
     --ignition-file coreos-infra.ign /dev/sdb
----


The CoreOS image for aarch64 is missing a set of binary blobs needed
for the Pi's Broadcom SOC. These have been compiled and packaged by
3rd parties and https://github.com/pftf/RPi4/releases[are available as
ZIP files from Github].

After the CoreOS installer places the default image on the SD card,
the contents of this zip file must be overlayed into the `boot`
partition. The installation docs above show how to do it
manually. I've included a script
link:scripts/prepare-pi.sh[prepare-pi.sh] That will do the whole job.

    bash scripts/prepare-pi.sh <device file> <ignition file>

You will be prompted by `sudo` twice for your password to execute a
couple of commands as root.

When the disk write is complete, you can remove the SD card and insert
it into your Pi4 and power it on. Be sure that the NIC is cabled on a
port that can reach the internet. It will perform the first-boot
actions and reboot. 


== Intel x86_64 - Live USB

For traditional Intel servers, it's not practical to remove the system
disk and apply the image in the way that you can with devices like the
Raspberry Pi. Instead, the image and configuration are written to a
bootable device like a USB stick. The configuration information
includes the target disk on new host. The image is copied to
the target disk and the configuration is applied. When the system
reboots, the system disk now contains the initial CoreOS system and
configuration.




== References

* https://coreos.github.io/coreos-installer/[coreos-installer] +
  Usage and arguments for the CoreOS installer binary.  This can be
  run from a live ISO or on a second host to write to the boot media.

* https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/[CoreOS
  on Bare Metal] +
  How to install CoreOS on Bare Metal. This includes variants for PXE,
  and Live ISO installations.

* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/[CoreOS
  on Raspberry Pi 4] +
  How to install CoreOS on Raspberry Pi 4 or 5. This includes
  instructions for installing EFI boot components that are not present
  in the Pi boot firmware.

* https://github.com/coreos/ignition[Ignition] +
  Ignition is the engine that applies the provided configuration to a
  new CoreOS instance on first boot.

* https://github.com/pbatard/UEFI-Shell[UEFI-Shell] +
  a UEFI Shell for built from EDK2 sources

* https://github.com/pftf/RPi4/[Raspberry Pi 4 UEFI Firmware Images] +
  A build of the UEFI-Shell specifically for Rasberry Pi 4
 
