---
#
#
#
dns:
  nameservers:
    pi4-1:
      fqdn: ns1.example.org
      device: enabcm6e4ei0
      ipv4: 192.168.2.10
    pi4-2:
      fqdn: ns1.example.org
      device: enabcm6e4ei0
      ipv4: 192.168.2.11

  forwarders:
    - 192.168.2.1
    - 1.1.1.1
    - 1.0.0.1
    
  zones:
    - fqdn: example.org
      file: example.org.zone
    - fqdn: lab.example.org
      file: lab.example.org.zone

  search:
    - lan    # mDNS from Google Mesh DNS
    - example.org
    - lab.example.org
