- name: Reload Systemd Units
  systemd_service:
    daemon_reload: true
  notify: Restart CoreDNS Service

- name: Restart CoreDNS Service
  service:
    name: coredns
    state: restarted
    enabled: true
