---
#
# Coordinate creating a coredns service container
#

#
# Prepare the configuration space on the host
#
- name: Place the Configration Files
  import_tasks: config_files.yaml
      
- name: Prepare Services
  import_tasks: systemd_service.yaml
    
