---
#
# The playbook creates a web server with an SSL cert that identifies
# a known network for Cloudflare Warp clients
#
- name: Cloudflare Beacon
  hosts: cloudflare_beacons
  become: true

  vars_files:
    - cloudflare.yaml

  roles:
    - cloudflare-beacon
