// CoreDNS server by Ansible Playbook
= DNS Service - CoreDNS

https://coredns.io[CoreDNS] was developed for use in
https://kubernetes.io/[Kubernetes] as a light-weight name server for
containerized services. For a small to medium sized network, CoreDNS
is much simpler to configure and operate than any of the production
quality alternatives.

== Running CoreDNS

The CoreDNS configuration consists of a single configuration file and
a set of  https://en.wikipedia.org/wiki/Zone_file[DNS zone
files]. The files can be contained in a single directory, commonly
`/opt/coredns`. The program looks for a file called `Corefile` in the
current working directory when it is invoked. 

CoreDNS is meant to be run in a software container. CoreOS provides
https://podman.io[`podman`], a drop-in CLI replacement for Docker and
the `runc` runtime.

DNS servers listen to UDP port 53 for queries. TCP port 53 is used for
some operations such as zone transfers and secure DNS. By default it
listens on all configured interfaces.

The configuration used in this example is meant for use inside a
firewalled network. It does not serve queries to devices outside the
local network. It is meant to provide a split-dns

The CoreDNS container image is always found here:

    docker.io/coredns/coredns:latest


== `coredns-server` Playbook

The goal of the `coredns-server` playbook is to install and configure
CoreDNS on a set of servers. The servers need to listen for and
respond to DNS queries on port 53/UDP on one of a set of listed IPv4
addresses. The service runs in a software container and is managed as
a `systemd` service.

The deployment steps can be grouped into four related sets of tasks:

1. Switch to static resolver
1. Configure network interface
1. Deploy CoreDNS configuration
1. Configure `systemd` service

For clarities sake these four are broken down into separate task files
in the `coredns-server` role. These are detailed in corresponding
sections link:#coredns-server-role[below].

An Ansible playbook is defined in a `.yaml` formatted file. It is
possible to contain the entire playbook in a single file, but it is
usually helpful to have the playbook use a *role*. Roles are re-usable
modules that 

.`coredns-server-pb.yaml`
[source,yaml]
----
---
#
# The playbook creates a DNS server on the target hosts using CoreDNS
# It populates the zone files from files/zones
#
- name: CoreDNS Server
  hosts: dnsservers
  become: true

  vars_files:
    - dns_services.yaml

  roles:
    - coredns-server
----

The `dns_services.yaml` file specifies the parameters for the CoreDNS
server. Among these are the locations and zones for the
https://en.wikipedia.org/wiki/Zone_file[zone files]. These reside in
`files/zones` in the ansible directory. The zone files here are static
and follow the RFC standards and will be familar to anyone who's
configured https://www.isc.org/bind/[ISC Bind]. They could be produced
mechanically from other databases but that is outside the scope of
this project.

[#coredns-server-role]
== `coredns-server` Role

.coredns-server role tree
----
roles/coredns-server/
├── files
│   └── coredns.container
├── handlers
│   └── main.yaml
├── tasks
│   ├── config_files.yaml
│   ├── main.yaml
│   ├── network.yaml
│   ├── resolver.yaml
│   └── systemd_service.yaml
└── templates
    ├── Corefile.j2
    └── resolv.conf.j2

5 directories, 9 files
----


=== `tasks\main.yaml`

The task files are the primary driver of a playbook and role. The rest
of the files provide resources that serve the tasks as they
are run. The file `main.yaml` acts as the entry point for the tasks
defined in the `tasks/` subdirectory. The tasks are defined as if they
were part of a playbook, as a YAML list. The `main.yaml` file refers
to a set of smaller task files, grouping the tasks functionally.

.`tasks\main.yaml`
--
include::./roles/coredns-server/tasks/main.yaml[]
--









== References

* https://coredns.io[CoreDNS]
* https://www.isc.org/bind/[ISC Bind]
* https://kerbernetes.io[Kubernetes]
* https://en.wikipedia.org/wiki/Zone_file[DNS Zone Files]
