---
intel:
  vars:
    ansible_user: core
    ansible_ssh_private_key_file: secret/infra-ansible-ed25519
  hosts:
    intel1:
      ansible_host: 192.168.2.14
    intel2:
      ansible_host: 192.168.2.27
    intel3:
       ansible_host: 192.168.2.24
rpi:
  vars:
    ansible_user: core
    ansible_ssh_private_key_file: secret/infra-ansible-ed25519
  hosts:
    pi4-1:
      ansible_host: 192.168.2.223
    pi3-1:
      ansible_host: 192.168.2.22
      ansible_user: mark
    pi3-2:
      ansible_host: 192.168.2.23
      ansible_user: mark

pilots:
  vars:
    ansible_user: mark
    ansible_ssh_private_key_file: secret/infra-ansible-ed25519
  hosts:
    kvm-1:
      ansible_host: 192.168.2.15
    kvm-2:
      ansible_host: 192.168.2.28
    kvm-3:
      ansible_host: 192.168.2.25
      ansible_user: pi
      

dnsservers:
  hosts:
    pi4-1:

cloudflare_beacons:
  hosts:
    pi4-1:

cloudflare_tunnels:
  hosts:
    pi4-1:
      tunnel_name: home
