---
infrastructure:
  vars:
    ansible_user: core
    ansible_ssh_private_key_file: secrets/infra-ansble-ed25519
  hosts:
    infra1:
      ansible_host: 192.168.2.185
    infra2:
      ansible_host: 192.168.2.184
